services:
  # Django App
  backend:
    container_name: django
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8090 --reload 
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    depends_on:
      - django_redis

  # Redis
  django_redis:
    image: redis
    container_name: django_redis
    ports:
      - "6379:6379"
      
  # Database
  django_db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=postgres  
      - POSTGRES_DB=django_db
    ports:  
      - "6432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: